//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpsViewEbaraV2NameSpace {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TpsViewEbaraV2NameSpace.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Axis 1.
        /// </summary>
        internal static string TXT_button_limitSTN1Axis1 {
            get {
                return ResourceManager.GetString("TXT_button_limitSTN1Axis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string TXT_button_Setting {
            get {
                return ResourceManager.GetString("TXT_button_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimit Axis 1.
        /// </summary>
        internal static string TXT_button_unLimitSTN1Axis1 {
            get {
                return ResourceManager.GetString("TXT_button_unLimitSTN1Axis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welding.
        /// </summary>
        internal static string TXT_button_WeldingParameter {
            get {
                return ResourceManager.GetString("TXT_button_WeldingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Arc Stable.
        /// </summary>
        internal static string TXT_checkBox_boolBlocksiFr1ArcStable {
            get {
                return ResourceManager.GetString("TXT_checkBox_boolBlocksiFr1ArcStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous.
        /// </summary>
        internal static string TXT_checkBox_boolContinuous {
            get {
                return ResourceManager.GetString("TXT_checkBox_boolContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Last Wobj.
        /// </summary>
        internal static string TXT_checkBox_boolKeepLastWobj {
            get {
                return ResourceManager.GetString("TXT_checkBox_boolKeepLastWobj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveL Substituted.
        /// </summary>
        internal static string TXT_checkBox_boolMoveLSubstituted {
            get {
                return ResourceManager.GetString("TXT_checkBox_boolMoveLSubstituted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic STN1.
        /// </summary>
        internal static string TXT_checkBox_boolUseAlignedSTNbyFixedValue {
            get {
                return ResourceManager.GetString("TXT_checkBox_boolUseAlignedSTNbyFixedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebara Utility.
        /// </summary>
        internal static string TXT_EbaraUtility {
            get {
                return ResourceManager.GetString("TXT_EbaraUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebara Utility.
        /// </summary>
        internal static string TXT_EbaraUtilityTitle {
            get {
                return ResourceManager.GetString("TXT_EbaraUtilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string TXT_PipeGrooveModelButton {
            get {
                return ResourceManager.GetString("TXT_PipeGrooveModelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe Groove Model.
        /// </summary>
        internal static string TXT_PipeGrooveModelTitle {
            get {
                return ResourceManager.GetString("TXT_PipeGrooveModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TXT_PipeGrooveType {
            get {
                return ResourceManager.GetString("TXT_PipeGrooveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string TXT_tabPage_Debug {
            get {
                return ResourceManager.GetString("TXT_tabPage_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string TXT_tabPage_Detail {
            get {
                return ResourceManager.GetString("TXT_tabPage_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string TXT_tabPage_Scan {
            get {
                return ResourceManager.GetString("TXT_tabPage_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string TXT_TpsFormSettingTitle {
            get {
                return ResourceManager.GetString("TXT_TpsFormSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welding Parameters.
        /// </summary>
        internal static string TXT_TpsFormWeldingParameterTitle {
            get {
                return ResourceManager.GetString("TXT_TpsFormWeldingParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string TXT_tpsLabel_Branch {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string TXT_tpsLabel_Header {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string TXT_tpsLabel_intGroupIndex {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_intGroupIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string TXT_tpsLabel_intIndex {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_intIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Arc Length.
        /// </summary>
        internal static string TXT_tpsLabel_numBlocksiArcStableLength {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numBlocksiArcStableLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        internal static string TXT_tpsLabel_numDiameter {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isometrical Saddle.
        /// </summary>
        internal static string TXT_tpsLabel_numIsometricalSaddleCoefficient {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numIsometricalSaddleCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string TXT_tpsLabel_numLayerNoStart {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numLayerNoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center X.
        /// </summary>
        internal static string TXT_tpsLabel_numSeamCenterX {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numSeamCenterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Angle.
        /// </summary>
        internal static string TXT_tpsLabel_numSeamNormalAngle {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numSeamNormalAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulder Coeff..
        /// </summary>
        internal static string TXT_tpsLabel_numShoulderGrooveCoefficient {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numShoulderGrooveCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSC Interval.
        /// </summary>
        internal static string TXT_tpsLabel_numTorchCleanIntervalCount {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numTorchCleanIntervalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R1 Scan.
        /// </summary>
        internal static string TXT_tpsLabel_Rob1Scan {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_Rob1Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R2 Scan.
        /// </summary>
        internal static string TXT_tpsLabel_Rob2Scan {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_Rob2Scan", resourceCulture);
            }
        }
    }
}
