//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpsViewEbaraV2NameSpace.zh {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class strings_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal strings_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TpsViewEbaraV2NameSpace.zh.strings.zh", typeof(strings_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 锁定1轴.
        /// </summary>
        internal static string TXT_button_limitSTN1Axis1 {
            get {
                return ResourceManager.GetString("TXT_button_limitSTN1Axis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string TXT_button_Setting {
            get {
                return ResourceManager.GetString("TXT_button_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解锁1轴.
        /// </summary>
        internal static string TXT_button_unLimitSTN1Axis1 {
            get {
                return ResourceManager.GetString("TXT_button_unLimitSTN1Axis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 焊接.
        /// </summary>
        internal static string TXT_button_WeldingParameter {
            get {
                return ResourceManager.GetString("TXT_button_WeldingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 屏蔽焊接状态信号.
        /// </summary>
        internal static string TXT_checkBox_boolBlocksiFr1ArcStable {
            get {
                return ResourceManager.GetString("TXT_checkBox_boolBlocksiFr1ArcStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连续焊接.
        /// </summary>
        internal static string TXT_checkBox_boolContinuous {
            get {
                return ResourceManager.GetString("TXT_checkBox_boolContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用上一次工件坐标系.
        /// </summary>
        internal static string TXT_checkBox_boolKeepLastWobj {
            get {
                return ResourceManager.GetString("TXT_checkBox_boolKeepLastWobj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 步进模式.
        /// </summary>
        internal static string TXT_checkBox_boolMoveLSubstituted {
            get {
                return ResourceManager.GetString("TXT_checkBox_boolMoveLSubstituted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动态计算变位机角度.
        /// </summary>
        internal static string TXT_checkBox_boolUseAlignedSTNbyFixedValue {
            get {
                return ResourceManager.GetString("TXT_checkBox_boolUseAlignedSTNbyFixedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试助手.
        /// </summary>
        internal static string TXT_EbaraUtility {
            get {
                return ResourceManager.GetString("TXT_EbaraUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试助手.
        /// </summary>
        internal static string TXT_EbaraUtilityTitle {
            get {
                return ResourceManager.GetString("TXT_EbaraUtilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模型.
        /// </summary>
        internal static string TXT_PipeGrooveModelButton {
            get {
                return ResourceManager.GetString("TXT_PipeGrooveModelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 焊缝模型.
        /// </summary>
        internal static string TXT_PipeGrooveModelTitle {
            get {
                return ResourceManager.GetString("TXT_PipeGrooveModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类别.
        /// </summary>
        internal static string TXT_PipeGrooveType {
            get {
                return ResourceManager.GetString("TXT_PipeGrooveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试.
        /// </summary>
        internal static string TXT_tabPage_Debug {
            get {
                return ResourceManager.GetString("TXT_tabPage_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 详细.
        /// </summary>
        internal static string TXT_tabPage_Detail {
            get {
                return ResourceManager.GetString("TXT_tabPage_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本.
        /// </summary>
        internal static string TXT_tabPage_Scan {
            get {
                return ResourceManager.GetString("TXT_tabPage_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string TXT_TpsFormSettingTitle {
            get {
                return ResourceManager.GetString("TXT_TpsFormSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 焊接参数.
        /// </summary>
        internal static string TXT_TpsFormWeldingParameterTitle {
            get {
                return ResourceManager.GetString("TXT_TpsFormWeldingParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支管.
        /// </summary>
        internal static string TXT_tpsLabel_Branch {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 母管.
        /// </summary>
        internal static string TXT_tpsLabel_Header {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工艺组.
        /// </summary>
        internal static string TXT_tpsLabel_intGroupIndex {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_intGroupIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        internal static string TXT_tpsLabel_intIndex {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_intIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 焊层连续最大长度.
        /// </summary>
        internal static string TXT_tpsLabel_numBlocksiArcStableLength {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numBlocksiArcStableLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直径.
        /// </summary>
        internal static string TXT_tpsLabel_numDiameter {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同径系数.
        /// </summary>
        internal static string TXT_tpsLabel_numIsometricalSaddleCoefficient {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numIsometricalSaddleCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 道次.
        /// </summary>
        internal static string TXT_tpsLabel_numLayerNoStart {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numLayerNoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位置 X.
        /// </summary>
        internal static string TXT_tpsLabel_numSeamCenterX {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numSeamCenterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 变位机角度.
        /// </summary>
        internal static string TXT_tpsLabel_numSeamNormalAngle {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numSeamNormalAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 肩部系数.
        /// </summary>
        internal static string TXT_tpsLabel_numShoulderGrooveCoefficient {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numShoulderGrooveCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清枪间隔次数.
        /// </summary>
        internal static string TXT_tpsLabel_numTorchCleanIntervalCount {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_numTorchCleanIntervalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R1 Scan.
        /// </summary>
        internal static string TXT_tpsLabel_Rob1Scan {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_Rob1Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R2 Scan.
        /// </summary>
        internal static string TXT_tpsLabel_Rob2Scan {
            get {
                return ResourceManager.GetString("TXT_tpsLabel_Rob2Scan", resourceCulture);
            }
        }
    }
}
